source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'delayed_job', ">= 4.0.0"
gem 'delayed_job_active_record', ">=4.0.0"
gem 'delayed_job_celluloid', :path => '..'
gem 'daemons'